### ISSUE TITLE
DTO and Authentication

### ISSUE THREAD

**Issue by SmythyCosta** [fsonmezay/generic-rest-api#2]
DTO and Authorization

Hi friend, this type of generic implementation is excellent.

do you think it is difficult to add to your GenericRest the logics for DTO and Authorization?

I am using your GenericRest but I could not implement this solution for DTO and Authorization.

**Comment by fsonmezay** [comment]
Hello @SmythyCosta ,
You can check [Java Generics Documentation](https://docs.oracle.com/javase/tutorial/java/generics/index.html)
